//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thermals_web.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Thermals_todaySoap")]
    public interface Thermals_todaySoap {
        
        // CODEGEN: Generating message contract since element name GetForecastJSONResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetForecastJSON", ReplyAction="*")]
        Thermals_web.ServiceReference1.GetForecastJSONResponse GetForecastJSON(Thermals_web.ServiceReference1.GetForecastJSONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetForecastJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<Thermals_web.ServiceReference1.GetForecastJSONResponse> GetForecastJSONAsync(Thermals_web.ServiceReference1.GetForecastJSONRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetForecastJSONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetForecastJSON", Namespace="http://tempuri.org/", Order=0)]
        public Thermals_web.ServiceReference1.GetForecastJSONRequestBody Body;
        
        public GetForecastJSONRequest() {
        }
        
        public GetForecastJSONRequest(Thermals_web.ServiceReference1.GetForecastJSONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetForecastJSONRequestBody {
        
        public GetForecastJSONRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetForecastJSONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetForecastJSONResponse", Namespace="http://tempuri.org/", Order=0)]
        public Thermals_web.ServiceReference1.GetForecastJSONResponseBody Body;
        
        public GetForecastJSONResponse() {
        }
        
        public GetForecastJSONResponse(Thermals_web.ServiceReference1.GetForecastJSONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetForecastJSONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetForecastJSONResult;
        
        public GetForecastJSONResponseBody() {
        }
        
        public GetForecastJSONResponseBody(string GetForecastJSONResult) {
            this.GetForecastJSONResult = GetForecastJSONResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Thermals_todaySoapChannel : Thermals_web.ServiceReference1.Thermals_todaySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Thermals_todaySoapClient : System.ServiceModel.ClientBase<Thermals_web.ServiceReference1.Thermals_todaySoap>, Thermals_web.ServiceReference1.Thermals_todaySoap {
        
        public Thermals_todaySoapClient() {
        }
        
        public Thermals_todaySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Thermals_todaySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Thermals_todaySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Thermals_todaySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Thermals_web.ServiceReference1.GetForecastJSONResponse Thermals_web.ServiceReference1.Thermals_todaySoap.GetForecastJSON(Thermals_web.ServiceReference1.GetForecastJSONRequest request) {
            return base.Channel.GetForecastJSON(request);
        }
        
        public string GetForecastJSON() {
            Thermals_web.ServiceReference1.GetForecastJSONRequest inValue = new Thermals_web.ServiceReference1.GetForecastJSONRequest();
            inValue.Body = new Thermals_web.ServiceReference1.GetForecastJSONRequestBody();
            Thermals_web.ServiceReference1.GetForecastJSONResponse retVal = ((Thermals_web.ServiceReference1.Thermals_todaySoap)(this)).GetForecastJSON(inValue);
            return retVal.Body.GetForecastJSONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Thermals_web.ServiceReference1.GetForecastJSONResponse> Thermals_web.ServiceReference1.Thermals_todaySoap.GetForecastJSONAsync(Thermals_web.ServiceReference1.GetForecastJSONRequest request) {
            return base.Channel.GetForecastJSONAsync(request);
        }
        
        public System.Threading.Tasks.Task<Thermals_web.ServiceReference1.GetForecastJSONResponse> GetForecastJSONAsync() {
            Thermals_web.ServiceReference1.GetForecastJSONRequest inValue = new Thermals_web.ServiceReference1.GetForecastJSONRequest();
            inValue.Body = new Thermals_web.ServiceReference1.GetForecastJSONRequestBody();
            return ((Thermals_web.ServiceReference1.Thermals_todaySoap)(this)).GetForecastJSONAsync(inValue);
        }
    }
}
